### ISSUE TITLE
Why it is always popping up to sign in with apple id, on launching my flutter app on ios device

### ISSUE THREAD

**Issue by imsumit0303** [akashmishra242/google_signin_without_firebase#1]
whenever I try to launch my app using ide through commands, app launches with a prompt dialogue asking sign in with apple app id and password.

I fill that as well and it directs me to go to settings and as settings opens I don't know what to do then. Going back to my it stops at splash screen and nothing happens. Closing the app and relaunch it through ide it repeats same.

I implemented google signin in my project. And in google_signin package documentation it was mentioned as below :

Note that according to https://developer.apple.com/sign-in-with-apple/get-started, starting June 30, 2020, apps that use login services must also offer a "Sign in with Apple" option when submitting to the Apple App Store.

I haven't implemented "Sign in with Apple" option yet so, is it happening because of this?

My requirement is to keep GoogleSignIn. If I implement "Sign in with Apple" option according to documentation. Will it stop asking signin with appleId on app launch?

If yes, Please help me to understand why it is is necessary even though signin with apple id option is not my requirement.

**Comment by ToushikBanik123** [comment]
Yes, the issue you're facing is most likely due to Apple's guideline from June 2020, requiring any app that uses third-party login services (like Google) to also offer "Sign in with Apple." Since this hasn't been implemented in your app, it's prompting for an Apple ID sign-in on launch.

However, there have been some updates as of 2024. Apple is no longer strictly enforcing the "Sign in with Apple" requirement in all cases. If your app provides an alternative login method that meets their privacy guidelines (like ensuring minimal data collection and allowing users to hide their email), this might also comply with their policies​.Despite this update, Apple still prioritizes enforcing privacy and their ecosystem rules, which can feel like they're maintaining their "walled garden." They won't necessarily follow our logic, and unfortunately, we have to adhere to their rules to get approval for App Store submissions​. To stop the Apple ID sign-in prompt, implementing "Sign in with Apple" will ensure compliance. Alternatively, you can explore privacy-compliant alternatives, but you'll still need to meet their strict guidelines.
